[tool.poetry]
name = "shared-lib-manager"
version = "0.1.0"
description = "A library for packages that ship shared libraries for other Python packages to use"
authors = ["Vyas Ramasubramani <vyasr@nvidia.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
