# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "shared_lib_manager"
version = "0.0.1"
description = "A library for packages that ship shared libraries for other Python packages to use"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Vyas Ramasubramani" },
]
license = { text = "Apache 2.0" }
# TODO: Determine minimum Python version. We may need to support earlier.
requires-python = ">=3.9"

[tool.poetry]
name = "shared_lib_manager"
version = "0.0.1"
description = "A library for packages that ship shared libraries for other Python packages to use"
authors = [
    "Vyas Ramasubramani <vyasr@nvidia.com>",
]
repository = "https://github.com/wheelnext/native_lib_loader/"

[tool.poetry.dependencies]
python = ">=3.09"
